const texto = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque iaculis quis ante eget sollicitudin. Maecenas a lectus odio. Vestibulum vulputate diam ac orci hendrerit, id egestas sem congue. Sed eu rutrum massa. Maecenas a tincidunt erat. Nam velit purus, laoreet id nisi in, elementum fringilla leo. Nam eu neque sed est iaculis viverra in id erat. Aenean id dolor eu lorem iaculis rhoncus sed at neque. Curabitur orci ex, lobortis et ultrices at, pharetra non diam.

Proin accumsan fringilla dui, in malesuada elit suscipit in. Donec sed lacus vitae est aliquet convallis. Nullam eleifend ut eros et sodales. Phasellus lectus elit, facilisis vitae libero vel, tempus hendrerit arcu. Vestibulum accumsan, velit a ullamcorper faucibus, dui urna tempus mi, eu ornare erat eros quis mi. Vestibulum convallis commodo pellentesque. Cras placerat quis enim et molestie. Sed lorem elit, porttitor eget aliquet ut, lobortis ac risus. Proin mollis suscipit urna, sed auctor tortor interdum eu. Nunc pellentesque dignissim velit at fermentum. Nunc cursus ullamcorper tempor. Vestibulum magna diam, fringilla id efficitur id, dapibus vitae lorem. Praesent lobortis nunc ac purus accumsan eleifend.

Cras tincidunt ante vel augue lobortis rutrum. In dignissim lectus dolor, nec bibendum ligula rhoncus sed. Maecenas neque lorem, sollicitudin vitae hendrerit ac, accumsan malesuada nibh. Donec leo erat, tristique a elit eget, ornare iaculis urna. Proin quis mollis orci. Sed sed laoreet sapien, quis dapibus neque. Sed consectetur, leo et sollicitudin molestie, nulla arcu volutpat leo, a lacinia dolor mauris vehicula metus. Fusce fermentum viverra hendrerit. Sed tristique diam varius pretium consectetur. Quisque eu pulvinar urna. Suspendisse potenti. Nullam sagittis urna dapibus velit vehicula, eget fermentum orci sollicitudin. Vestibulum ac rhoncus sapien.

Mauris finibus ante nec libero tempus, euismod accumsan urna pellentesque. Nullam ornare ex mi, eget viverra nibh tincidunt id. Aliquam non libero id neque rhoncus ultricies. Suspendisse vel lobortis ex. Curabitur malesuada, urna eget euismod eleifend, mauris ipsum mattis metus, a dictum tellus justo sit amet lacus. Nullam laoreet euismod fringilla. Mauris venenatis consectetur volutpat. Morbi mollis purus sit amet scelerisque mollis. Maecenas pretium mi dui, accumsan semper leo placerat nec. Aenean congue est nibh, vel euismod nisi viverra blandit. Sed convallis suscipit eleifend.

Fusce euismod sagittis sem, sit amet efficitur neque ornare vitae. Nunc et nisi porttitor, imperdiet leo sed, porttitor nibh. Ut fermentum arcu sapien. Mauris vestibulum non urna quis aliquet. Phasellus sagittis diam vel mi ultricies dapibus. Cras ultricies turpis eget lorem auctor eleifend. Donec molestie dictum ex ut lacinia. Fusce dapibus ante non arcu malesuada tristique. Aliquam erat volutpat. Suspendisse nisi elit, lobortis et varius ac, porttitor sed dolor. Vivamus sit amet arcu sit amet velit facilisis pulvinar. Morbi a suscipit urna, quis fermentum eros. Mauris ac nisl nunc. Suspendisse imperdiet ante nec neque ullamcorper pellentesque. Nam cursus odio eget leo tempus fermentum.`

console.log(texto.match(/(Lorem|Ipsum)/g));